name: cp255
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.14
  - pip
  - pandas
  - geopandas
  - numpy
  - openpyxl         
  - xlrd              
  - requests
  - pdfplumber
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - pip:
    - jenkspy
    - censusgeocode